from rest_framework.authentication import TokenAuthentication

class BearerAuthentication(TokenAuthentication):
    """
    Bearer authentication scheme for Django Rest Framework.
    """

    # the default Token scheme doesn't work with Interact option of
    # autogenerated docs
    keyword = 'Bearer'
